
services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: requests
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  frontend:
    image: react-app
    ports:
      - 3000:3000

  backend:
    image: django-app
    ports: 
      - 8000:8000
    depends_on:
      - db

volumes:
  data:
